export const CLIENT_DETAILS_REQUEST = 'CLIENT_DETAILS_REQUEST'
export const CLIENT_DETAILS_SUCCESS = 'CLIENT_DETAILS_SUCCESS'
export const CLIENT_DETAILS_FAIL = 'CLIENT_DETAILS_FAIL'

export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST'
export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS'
export const CLIENT_LIST_FAIL = 'CLIENT_LIST_FAIL'

export const CLIENT_DELETE_REQUEST = 'CLIENT_DELETE_REQUEST'
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS'
export const CLIENT_DELETE_FAIL = 'CLIENT_DELETE_FAIL'

export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST'
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS'
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL'
export const CLIENT_CREATE_RESET = 'CLIENT_CREATE_RESET'

export const CLIENT_EDIT_REQUEST = 'CLIENT_EDIT_REQUEST'
export const CLIENT_EDIT_SUCCESS = 'CLIENT_EDIT_SUCCESS'
export const CLIENT_EDIT_FAIL = 'CLIENT_EDIT_FAIL'
export const CLIENT_EDIT_RESET = 'CLIENT_EDIT_RESET'
