export const ORDER_STATUS_LIST_REQUEST = 'ORDER_STATUS_LIST_REQUEST'
export const ORDER_STATUS_LIST_SUCCESS = 'ORDER_STATUS_LIST_SUCCESS'
export const ORDER_STATUS_LIST_FAIL = 'ORDER_STATUS_LIST_FAIL'
