export const STATS_MASTERS_REQUEST = 'STATS_MASTERS_REQUEST'
export const STATS_MASTERS_SUCCESS = 'STATS_MASTERS_SUCCESS'
export const STATS_MASTERS_FAIL = 'STATS_MASTERS_FAIL'

export const STATS_MANAGERS_REQUEST = 'STATS_MANAGERS_REQUEST'
export const STATS_MANAGERS_SUCCESS = 'STATS_MANAGERS_SUCCESS'
export const STATS_MANAGERS_FAIL = 'STATS_MANAGERS_FAIL'
