export const STATS_MASTERS_REQUEST = 'STATS_MASTER_REQUEST'
export const STATS_MASTERS_SUCCESS = 'STATS_MASTER_SUCCESS'
export const STATS_MASTERS_FAIL = 'STATS_MASTER_FAIL'

export const STATS_MANAGERS_REQUEST = 'STATS_MANAGER_REQUEST'
export const STATS_MANAGERS_SUCCESS = 'STATS_MANAGER_SUCCESS'
export const STATS_MANAGERS_FAIL = 'STATS_MANAGER_FAIL'
