export const smartphones = [
  'BlackBerry Motion',
  'Essential Phone',
  'HTC U Play',
  'HTC U Ultra',
  'HTC U11',
  'Huawei Honor 8 Pro',
  'Huawei Honor 9',
  'Huawei Mate 10',
  'Huawei P10',
  'IPhone 8',
  'IPhone 8 Plus',
  'IPhone X',
  'LG Fiesta',
  'LG G6',
  'LG K10 (2017)',
  'LG V30',
  'Meizu M6 Note',
  'Moto C',
  'Moto G5',
  'Moto X4',
  'Moto Z2 Play',
  'Nokia 2',
  'Nokia 3',
  'Nokia 5',
  'Nokia 6',
  'Nokia 7',
  'Nokia 8',
  'Nokia 105 (2017)',
  'Nokia 130 (2017)',
  'Nokia 3310 (2017)',
  'OnePlus 5',
  'OnePlus 5T',
  'Oppo R11',
  'Pixel 2',
  'Razer Phone',
  'Samsung Galaxy A3 (2017)',
  'Samsung Galaxy A5 (2017)',
  'Samsung Galaxy A7 (2017)',
  'Samsung Galaxy C5',
  'Samsung Galaxy J2 (2017)',
  'Samsung Galaxy J5 (2017)',
  'Samsung Galaxy J7 Pro (2017)',
  'Samsung Galaxy Note 7',
  'Samsung Galaxy Note 8',
  'Samsung Galaxy S8',
  'Samsung Galaxy Tab S3',
  'Samsung Galaxy Xcover 4',
  'Sony Xperia XA1',
  'Sony Xperia XZ Premium',
  'Sony Xperia XZ1',
  'Sony Xperia XZ1 Compact',
  'Sony Xperia XZs',
  'Xiaomi Mi A1',
  'Xiaomi Mi Max 2',
  'Xiaomi Mi MIX 2',
  'Xiaomi Redmi 5',
  'Xiaomi Redmi Note 4',
  'Xiaomi Redmi Note 5A',
  'Asus ZenFone 5',
  'Asus ZenFone 5Z',
  'HTC U12+',
  'Huawei Mate 20',
  'Huawei P20',
  'Infinix Hot S3',
  'IPhone XR',
  'IPhone XS',
  'IPhone XS Max',
  'LG G7 ThinQ',
  'LG K10 (2018)',
  'LG V40 ThinQ',
  'Moto G6',
  'Moto Z3',
  'Nokia 6.1',
  'Nokia 7 Plus',
  'Nokia 7.1',
  'Nokia 8 Sirocco',
  'Nokia 8.1',
  'Nokia 8110 4G',
  'Nubia X',
  'OnePlus 6',
  'OnePlus 6T',
  'Oppo F7',
  'Oppo F9',
  'Oppo Find X',
  'Oppo R17',
  'Pixel 3',
  'Red Hydrogen One',
  'Redmi Note 5',
  'ROG Phone',
  'Samsung Galaxy A6 / A6+',
  'Samsung Galaxy A6s',
  'Samsung Galaxy A7 (2018)',
  'Samsung Galaxy A8 (2018)',
  'Samsung Galaxy A8 Star',
  'Samsung Galaxy A8s',
  'Samsung Galaxy A9 (2018)',
  'Samsung Galaxy Note 9',
  'Samsung Galaxy S9',
  'Sony Xperia XZ2',
  'Sony Xperia XZ2 Compact',
  'Sony Xperia XZ2 Premium',
  'Vivo NEX',
  'Vivo NEX Dual Display',
  'Vivo V9',
  'Xiaomi Mi 8',
  'Xiaomi Mi 8 EE',
  'Xiaomi Mi A2',
  'Xiaomi Mi Max 3',
  'Xiaomi Mi MIX 2S',
  'Xiaomi Mi MIX 3',
  'Xiaomi Pocophone F1',
  'Xiaomi Redmi Note 6 Pro',
  'Huawei Mate X',
  'Huawei P30',
  'LG G8 ThinQ',
  'LG V50 ThinQ 5G',
  'Moto G7',
  'Nokia 9 PureView',
  'Oppo Reno',
  'Pixel 3a',
  'Redmi Go',
  'Samsung Galaxy A80',
  'Samsung Galaxy Fold',
  'Samsung Galaxy M10',
  'Samsung Galaxy M20',
  'Samsung Galaxy M30',
  'Samsung Galaxy S10',
  'Sony Xperia 1',
  'Sony Xperia XA1 Plus',
  'Xiaomi Mi 9',
]
